### ISSUE TITLE
allow users to bypass xml to JSON conversion

### ISSUE THREAD

**Issue by jasonrberk** [JupiterOne/veracode-client#14]
https://github.com/JupiterOne/veracode-client/blob/master/package.json#L31

https://github.com/JupiterOne/veracode-client/blob/master/src/VeracodeClient.js#L95

there doesn't appear to be a way to bypass the XML to JSON conversion.  I'd love to make a PR that would allow such behavior.  

the current converter does't handle empty array or an array of one nicely.  https://www.npmjs.com/package/xml2js is _much_ more configurable and appears more supported.  

I would like to make a PR.  Would you prefer:

A) just a way to bypass the converter and return raw xml
B) do option "A" and switch the converter to `xml2js` as the default converter
C) let the caller provide a callback to perform the conversion

**Comment by jasonrberk** [comment]
https://github.com/jasonrberk/veracode-client/branches 

just something dirty off the top of my head....I'd obviously update docs and what not...  

thoughts?

**Comment by aiwilliams** [comment]
Hello @jasonrberk, thank you for your contribution! I'm not the original author, but I have the ability to merge PRs, so... 😄

I don't know all the ways the client is being used, so it is probably best to make the XML conversion flexible, providing an option to bypass the converter, leaving the default as it is now so that this can be a minor version release and other projects are not required to adjust to different JSON.

**Comment by jasonrberk** [comment]
those were my thoughts exactly.....any preference on the name of the the option to bypass?  

I was thinking `options.asXml` and the default is `false`.  When set `true`, just return the raw xml string

**Comment by aiwilliams** [comment]
Sounds good to me! Thanks @jasonrberk.

I'm a little disappointed that a function named `_xmlRequest()` is returning JSON at all, so it doesn't hurt too much more to return JSON **or** XML 😆

**Comment by jasonrberk** [comment]
@aiwilliams I am at a cross road in my sprint.  If I was to get this PR up and working, what turnaround time can I expect on your end?  If it can happen "quickly", I'll get the PR pushed up today.  If you think it will take more than a day or two to merge and publish, I'll have to wait till next sprint (starting 2/12)

thoughts?

**Comment by aiwilliams** [comment]
@jasonrberk I can get it approved, merged, and publish before the weekend 👍 Thanks!

**Comment by jasonrberk** [comment]
FYI - I ran all the tests on master before I did any work, and the ITs seem to pass, but exit with an error:

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        27.274s, estimated 38s
Ran all test suites matching /test\//i.
error Command failed with exit code 1.
```

**Comment by aiwilliams** [comment]
@jasonrberk PR merged, and I updated Travis to work and publish, now version `0.4.0` is out there. Thanks!

Closed by #15

**Comment by jasonrberk** [comment]
thanks for being so responsive @aiwilliams

**Comment by jasonrberk** [comment]
@aiwilliams - I broke it 👎 it won't affect anyone until they try to use the new "bypass" functionality.  would you like to open a new issue or just reopen this one?  I'll get the PR to fix it up pretty quick here

**Comment by aiwilliams** [comment]
We'll just re-open this one. Thanks for identifying any problems and addressing!

**Comment by jasonrberk** [comment]
I updated and my branch now works when using the client to return raw XML
